### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by vendethiel** [vendethiel/ezarena#53]
Since it seems I have users now (hi @winzombie @Phosphorus-M), I'm going to make it clearer what I want to work on...

This is the roadmap for 2.0.0

 - [ ] Fix #31 
 - [ ] Make sure #29 doesn't happen anymore (I think DB collation is to blame)
 - [ ] Rewrite the spellbook, like I rewrote the recipes book (it still uses a godawful ugly design)
 - [ ] Optimize `adr_battle` a bit more. I simplified a lot of code, I'm sure I can still do better.
 - [ ] TEST TEST TEST TEST. I'm sure there are still many bugs, because there are so many mods interacting with each other. If you guys can help me by testing and reporting bugs, I'm able to fix them.

Finally, from #51: either port the AD&R to Icy Phoenix (I already did port the code, templates will take some time) OR add a plugins system to EzArena so we can have mods without editing the code.

**Comment by vendethiel** [comment]
- [ ] adr_beggar / adr_lake / adr_temple:
  probably should rewrite mod, use table phpbb_adr_donations (id, item_id, chance, type). Currently they're all shared...
- [ ] potion effect: pet hp/mp
- [ ] rabbitoshi : resurrect pet cost per level (base cost + multiplier)
- [ ] make sure MP potions work

**Comment by winzombie** [comment]
pvp doesn't work, dont show actions

**Comment by vendethiel** [comment]
open an issue

**Comment by vendethiel** [comment]
@winzombie have you had the issue of your combat lot truncating? (i.e. you somehow lose half of it or so)

**Comment by vendethiel** [comment]
- [ ] fix PVP (yes, this is down on my priorities list)

**Comment by vendethiel** [comment]
Updated the list

**Comment by vendethiel** [comment]
We're nearing 2.0.0.

New spellbook
Fixes for PvP
Fixes for quests
